[package]
name = "terra"
version = "0.1.0"
authors = ["ltzz <ltzz@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio= "0.6.0"

[dependencies.gtk]
version = "0.6.0"
features = ["v3_24"]